"""Internal helpers for deprecation messages.

``ovos_config/version.py`` is regenerated by CI on every release, so any
constant that must survive across releases lives here instead of being
added to that file.
"""
from ovos_config.version import VERSION_MAJOR

# Deprecations are removed at the next major bump.
NEXT_MAJOR_VERSION = f"{VERSION_MAJOR + 1}.0.0"
