name: Run Build Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  py_build_tests:
    uses: neongeckocom/.github/.github/workflows/python_build_tests.yml@master
    with:
      test_pipaudit: true
      # PYSEC-2023-228 is a pip vulnerability that only exists in the pipeline
      # GHSA-9wx4-h78v-vm56 is problematic but it's an issue upstream
      pipaudit_ignored: "GHSA-r9hx-vwmv-q579 PYSEC-2022-43012 GHSA-j8r2-6x86-q33q PYSEC-2023-228 GHSA-9wx4-h78v-vm56"
