name: Run UnitTests
on:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - "ovos_config/version.py"
      - "examples/**"
      - ".github/**"
      - ".gitignore"
      - "LICENSE"
      - "CHANGELOG.md"
      - "MANIFEST.in"
      - "readme.md"
      - "scripts/**"
  push:
    branches:
      - master
    paths-ignore:
      - "ovos_config/version.py"
      - "requirements/**"
      - "examples/**"
      - ".github/**"
      - ".gitignore"
      - "LICENSE"
      - "CHANGELOG.md"
      - "MANIFEST.in"
      - "readme.md"
      - "scripts/**"
  workflow_dispatch:

jobs:
  unit_tests:
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev swig libssl-dev
          python -m pip install build wheel
      - name: Install core repo
        run: |
          pip install .
      - name: Install test dependencies
        run: |
          pip install -r requirements/tests.txt
      - name: Run unittests
        run: |
          pytest --cov=ovos_config --cov-report xml test/unittests
          # NOTE: additional pytest invocations should also add the --cov-append flag
          #       or they will overwrite previous invocations' coverage reports
          #       (for an example, see OVOS Skill Manager's workflow)
      - name: Upload coverage
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        uses: codecov/codecov-action@v4
